version: '3.3'
services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: jboss/keycloak
    ports:
      - "6500:8080"
    environment:
     KEYCLOAK_ADMIN: admin
     KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin

    volumes:
      - ./keycloak/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./keycloak/themes/jumbo:/opt/jboss/keycloak/themes/jumbo
      - ./keycloak/themes/demo:/opt/jboss/keycloak/themes/demo
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
