version: '3.3'
services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: jboss/keycloak
    ports:
      - "6500:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./keycloak/themes/jumbo:/opt/jboss/keycloak/themes/jumbo
    restart: always
